Реализация функционала вещей и пользователей в памяти и создание моде…
ArinaYakovleva/java-shareit pull request #1
Opened 2022-09-12 23:54 UTC by ArinaYakovleva

…лей других сущностей

2022-09-13 06:12 UTC, Frilock requested changes
Добрый день, в целом мне все понравилось, оставил пару небольших комментариев к Вашей работе. Если будут какие то вопросы или с чем то будете не согласны можете написать мне в Slack. 
Кроме того, не знаю советовали ли Вам это или нет, но предлагаю в IDEA установить плагин sonarlint. Это статический анализатор кода, подсветит места с потенциальными проблемами и подскажет ряд хороших практик в написании кода.

2022-09-13 06:12 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        if (item != null && !item.getOwnerId().equals(ownerId)) {
А item.getOwnerId() null не вернет? На самом объекте item валидации по этому полю не вижу. Просто если вернется null то будет NPE. Чтобы избегать таких вещей можете использовать null safe equals - Objects.equals(o1, o2). Если же точно знаете что null не будет, то можете оставить

2022-09-13 06:12 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public interface UserService extends BaseUserService {
Вообще кажется, что если у Вас тут только 1 метод и это delete то лучше называть как то DeleteUserService, возможно вы закладываете логику расширения, но пока все таки тут только один метод удаления.
Кроме того, можно сделать один базовый интерфейс с типизацией (через дженерик), чтобы под каждую сущность не создавать одинаковый.

2022-09-13 06:12 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +                .anyMatch(user -> user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userDto.getId()));
Аналогичный вопрос, не получится ли что getEmail вернет null?

2022-09-14 18:15 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private final Long bookerId;
не совсем поняла, а в чем тут опечатка?)

2022-09-16 13:22 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    private final Long bookerId;
bookerId - это айди пользователя, который осуществил бронирование

2022-09-16 13:23 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImpl.java
> +        if (item != null && !item.getOwnerId().equals(ownerId)) {
Исправлено

2022-09-16 13:23 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImpl.java
> +                .anyMatch(user -> user.getEmail().equals(userDto.getEmail()) && !user.getId().equals(userDto.getId()));
Исправлено

2022-09-16 13:26 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +public interface UserService extends BaseUserService {
Тут в итоге я создала один интерфейс для вещей и один для пользователей. Совместить эти два интерфейса не выйдет, так как слишком много различий (в вещах в аргументах методов много где используется ownerId)

2022-09-16 14:34 UTC, Frilock approved these changes
Принято

2022-09-30 12:12 UTC, merged