Подключение JPA + создание функционала аренды и отзывов
ArinaYakovleva/java-shareit pull request #2
Opened 2022-10-05 21:57 UTC by ArinaYakovleva

Реализованы задачи 14 спринта, прошлые MockMvc тесты пока убрала, так как написаны были довольно коряво а исправлять долго, в следующем спринте будем проходить MockMvc, напишу лучше заново.

2022-10-06 11:30 UTC, Frilock requested changes
Добрый день, небольшой комментарий про размерность полей в модели. В остальном, на мой взгляд, все ок.

2022-10-06 11:30 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (item.getOwner().getId().equals(bookerId)) {
а owner всегда присутствует?

2022-10-06 19:44 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        if (item.getOwner().getId().equals(bookerId)) {
я поставила constraint not null в schema.sql, теперь не может) а если айди владельца нет в таблице items, то выкинется исключение, так что null быть не должно

2022-10-06 19:45 UTC, ArinaYakovleva commented on src/main/resources/schema.sql
> +    description VARCHAR NOT NULL,
Флаги указала, длину, где 255 не стала указывать в классах моделей, так как там это дефолтное значение

2022-10-07 08:12 UTC, Frilock commented on src/main/resources/schema.sql
> +    description VARCHAR NOT NULL,
Про дефолтное значение это ясно, я имею ввиду, что когда таблицы и поля проектируете нужно продумать размерность полей, а затем в Column их указать.

2022-10-07 08:13 UTC, Frilock approved these changes
Принято

2022-10-10 18:51 UTC, merged