Добавлен функционал запросов вещей + тесты
ArinaYakovleva/java-shareit pull request #3
Opened 2022-11-16 14:28 UTC by ArinaYakovleva

2022-11-17 17:32 UTC, Frilock requested changes
Добрый вечер, оставил несколько комментариев к работе. Основной комментарий по тестам, Вы то ставите модификаторы поля, то нет, в чем логика я не понял. Тестовый код должен быть такой же чистый как и основной. Кроме того, над большинством тестовых классов вешаете аннотацию очистки контекста, а она нужна Вам? Это тяжелая операция. 
Кроме того, не увидел достаточно негативных тестов, проверяющих негативные сценарии работы программы.

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    List<Booking> findAllOverlappedBookings(Long itemId, LocalDateTime start, LocalDateTime end);
А зачем вы над почти всеми методами sql пишите? Вроде ведь spring-data используйте, где можно в имя метода уложиться. Вроде не такие сложные тут запросы

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/common/CustomPageRequest.java
> +    int from;
модификатор приватный потеряли

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      public ItemServiceImpl(ItemRepository repository,
Чтоб такой большой конструктор не делать можно воспользоваться аннотацией от lombok - RequiredArgsConstructor

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      private static final String errorNotFound = "Вещь с id=%d не найдена";
У Вас private static final поле - их по Java конвенции принято писать в таком формате - ERROR_NOT_FOUND

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                log.info(request.toString());
Предлагаю в лог вывести какое то более информативное сообщение, а то выведете request и чего?)

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/RequestRepository.java
> +    @Query("select r from Request r " +
По моему тоже можно в названии метода уложиться

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +                .stream().map(this::getRequestDto)
map по хорошему на другую строчку надо перенести, так принято, каждая операция на новой строке

2022-11-17 17:32 UTC, Frilock commented on src/main/java/ru/practicum/shareit/request/dto/RequestDTOMapper.java
> +public abstract class RequestDTOMapper {
А зачем абстрактным делать? Можно final сделать

2022-11-17 17:32 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +    BookingRepository bookingRepository;
Почему в тестах Вы не ставите модификаторы у полей?

2022-11-17 17:32 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +@Transactional
А зачем транзакцию на каждый тест вешать?

2022-11-17 17:32 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
А Вам надо контекст каждый раз обновлять? Это тяжелая операция, вообще бы стараться ее избегать

2022-11-17 17:32 UTC, Frilock commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +        ItemDto createdItem = itemService.addItem(itemDto, 1L);
Еще можно вызывать методы используя assertDoesNotThrow и assertThrow, а то не вижу у Вас негативных тестов

2022-11-28 00:06 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/common/CustomPageRequest.java
> +    int from;
исправлено

2022-11-28 00:06 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      public ItemServiceImpl(ItemRepository repository,
исправлено

2022-11-28 00:07 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      private static final String errorNotFound = "Вещь с id=%d не найдена";
исправлено

2022-11-28 00:07 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                log.info(request.toString());
исправлено

2022-11-28 00:07 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/request/RequestRepository.java
> +    @Query("select r from Request r " +
исправлено

2022-11-28 00:08 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/request/RequestServiceImpl.java
> +                .stream().map(this::getRequestDto)
исправлено

2022-11-28 00:08 UTC, ArinaYakovleva commented on src/main/java/ru/practicum/shareit/request/dto/RequestDTOMapper.java
> +public abstract class RequestDTOMapper {
исправлено

2022-11-28 00:09 UTC, ArinaYakovleva commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +    BookingRepository bookingRepository;
исправлено

2022-11-28 00:10 UTC, ArinaYakovleva commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +@Transactional
исправлено

2022-11-28 00:14 UTC, ArinaYakovleva commented on src/test/java/ru/practicum/shareit/booking/BookingJsonTest.java
> +    User user = new User(1L, "Alex", "alex@mail.com");
исправлено

2022-11-28 00:14 UTC, ArinaYakovleva commented on src/test/java/ru/practicum/shareit/item/ItemServiceImplTest.java
> +        ItemDto createdItem = itemService.addItem(itemDto, 1L);
исправлено

2022-11-28 14:46 UTC, Frilock commented on src/test/java/ru/practicum/shareit/booking/BookingDbIntegrationTest.java
> +@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
Обсудили

2022-11-28 14:46 UTC, Frilock approved these changes
Принято

2023-01-17 11:43 UTC, merged